### ISSUE TITLE
Greenwave 502s on packages built from a .src.rpm

### ISSUE THREAD

**Issue by AdamWill** [release-engineering/greenwave#218]
Per @nirik , Koji admins can accidentally build packages from .src.rpms . He did so in https://bodhi.fedoraproject.org/updates/FEDORA-2023-7c0c58a874 (it's since been fixed, so you won't see the problem on loading that page any more), and we found that this isn't handled very well by greenwave/bodhi. In Bodhi the test gating status gets stuck as 'waiting' and you never see any test results (though tests have actually run, you can see them in openQA). If you go to the browser dev tools you can see why: Bodhi gets a 502 back from greenwave, because greenwave winds up on an unhandled error path. Kevin got the traceback out of greenwave's logs, here it is:

    [2023-12-05 01:44:53] [16] [ERROR] root: Failed to retrieve policies for Subject(<SubjectType 'koji_build'>, 'collectd-5.12.0-34.fc40')
    Traceback (most recent call last):
    File "/venv/lib64/python3.11/site-packages/greenwave/policies.py", line 597, in _get_sub_policies
    for remote_policies_url in _remote_urls(subject, url_templates):
    File "/venv/lib64/python3.11/site-packages/greenwave/policies.py", line 71, in _remote_urls
    pkg_namespace, pkg_name, rev = greenwave.resources.retrieve_scm_from_koji(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/venv/lib64/python3.11/site-packages/greenwave/resources.py", line 239, in retrieve_scm_from_koji
    return retrieve_scm_from_koji_build(nvr, source, koji_url)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/venv/lib64/python3.11/site-packages/greenwave/resources.py", line 259, in retrieve_scm_from_koji_build
    raise BadGateway(
    werkzeug.exceptions.BadGateway: 502 Bad Gateway: Failed to parse SCM URL "collectd-5.12.0-34.fc40.src.rpm" from Koji build "collectd-5.12.0-34.fc40" at "https://koji.fedoraproject.org/kojihub" (missing URL fragment with SCM revision information)
    [2023-12-05 01:44:53] [16] [INFO] greenwave.app_factory: HTTP request failed: 502 Bad Gateway: Unexpected error while fetching remote policies

we can handle this in `_get_sub_policies` and send a response with `FailedFetchRemoteRuleYaml`, I think (like we do if we don't find the build in Koji at all). That should cause Bodhi to provide more useful info in the web UI (and show the test results), and we would get the actual error message in the Greenwave JSON response (rather than having to get it out of greenwave's logs).

I've written an untested change to do this, but it's late, so I'm filing this issue just to make sure we don't forget about the problem or lose the traceback. I'll try and come back to this tomorrow.

**Comment by AdamWill** [comment]
https://github.com/release-engineering/greenwave/pull/220 would address this.

**Comment by hluk** [comment]
@AdamWill Your patch has been deployed to greenwave.fedoraproject.org. Feel free to test it and thanks for the fix.
